//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Refactor {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Refactor.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 setools	3
        ///glibc	1
        ///python3	2
        ///libselinux	2
        ///libsepol	2
        ///python-setuptools	3
        ///basesystem	1
        ///bash	2
        ///tzdata	2
        ///chkconfig	2
        ///openssl	2
        ///python-pip	2
        ///gdbm	2
        ///bzip2	2
        ///libxcrypt	2
        ///expat	2
        ///libffi	2
        ///xz	2
        ///ncurses	2
        ///libnsl2	2
        ///readline	2
        ///sqlite	2
        ///libtirpc	3
        ///zlib	2
        ///pcre2	2
        ///filesystem	1
        ///setup	1
        ///anolis-release	1
        ///popt	2
        ///coreutils	1
        ///ca-certificates	2
        ///crypto-policies	2
        ///grep	2
        ///texinfo	3
        ///e2fsprogs	2
        ///krb5	2
        ///util-linux	2
        ///fuse	2
        ///gawk	3
        ///keyutils	2
        ///libverto	2
        ///sed	3
        ///acl	2
        ///attr	2
        ///libcap	2
        ///gmp	2
        ///mpf [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string human_mysql {
            get {
                return ResourceManager.GetString("human_mysql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 gmp	2
        ///glibc	1
        ///basesystem	1
        ///bash	2
        ///libselinux	2
        ///tzdata	2
        ///filesystem	1
        ///setup	1
        ///ncurses	2
        ///pcre2	2
        ///libsepol	2
        ///python3	2
        ///chkconfig	2
        ///openssl	2
        ///python-setuptools	2
        ///python-pip	2
        ///gdbm	2
        ///bzip2	2
        ///libxcrypt	2
        ///expat	2
        ///libffi	2
        ///xz	2
        ///libnsl2	2
        ///readline	2
        ///sqlite	2
        ///libtirpc	3
        ///zlib	2
        ///popt	2
        ///coreutils	1
        ///ca-certificates	2
        ///crypto-policies	2
        ///grep	2
        ///texinfo	3
        ///e2fsprogs	2
        ///krb5	2
        ///util-linux	2
        ///fuse	2
        ///gawk	3
        ///keyutils	2
        ///libverto	2
        ///sed	3
        ///acl	2
        ///attr	2
        ///libcap	2
        ///mpfr	2
        ///libsigsegv	2
        ///pcre	2
        ///an [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string human_nginx {
            get {
                return ResourceManager.GetString("human_nginx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sqlite -1
        ///zstd -1
        ///mpfr	2
        ///gmp	2
        ///glibc	1
        ///basesystem	1
        ///bash	2
        ///libselinux	2
        ///tzdata	2
        ///filesystem	1
        ///setup	1
        ///ncurses	2
        ///pcre2	2
        ///libsepol	2
        ///python3	2
        ///chkconfig	2
        ///openssl	2
        ///python-setuptools	2
        ///python-pip	2
        ///gdbm	2
        ///bzip2	2
        ///libxcrypt	2
        ///expat	2
        ///libffi	2
        ///xz	2
        ///libnsl2	2
        ///readline	2
        ///libtirpc	3
        ///zlib	2
        ///popt	2
        ///ca-certificates	2
        ///crypto-policies	2
        ///grep	2
        ///texinfo	3
        ///e2fsprogs	2
        ///krb5	2
        ///util-linux	2
        ///fuse	2
        ///gawk	3
        ///keyutils	2
        ///libverto	2
        ///sed	3
        ///coreutils	1
        ///acl	2
        ///attr	2
        ///libcap	2
        ///libsigsegv	2
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string human_redis {
            get {
                return ResourceManager.GetString("human_redis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 a 0
        ///b 0
        ///c 0
        ///d 0
        ///e 0
        ///f 0
        /// 的本地化字符串。
        /// </summary>
        internal static string human_test {
            get {
                return ResourceManager.GetString("human_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 digraph MyPicture {
        ///	graph [rankdir=LR]
        ///	setools
        ///	setools -&gt; glibc
        ///	setools -&gt; python3
        ///	setools -&gt; libselinux
        ///	setools -&gt; libsepol
        ///	setools -&gt; &quot;python-setuptools&quot;
        ///	glibc
        ///	glibc -&gt; basesystem
        ///	glibc -&gt; bash
        ///	glibc -&gt; libselinux
        ///	glibc -&gt; tzdata
        ///	python3
        ///	python3 -&gt; bash
        ///	python3 -&gt; chkconfig
        ///	python3 -&gt; openssl
        ///	python3 -&gt; glibc
        ///	python3 -&gt; &quot;python-setuptools&quot;
        ///	python3 -&gt; &quot;python-pip&quot;
        ///	python3 -&gt; gdbm
        ///	python3 -&gt; bzip2
        ///	python3 -&gt; libxcrypt
        ///	python3 -&gt; expat
        ///	python3 -&gt; libffi
        ///	pytho [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string input_mysql {
            get {
                return ResourceManager.GetString("input_mysql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 digraph MyPicture {
        ///	graph [rankdir=LR]
        ///	gmp
        ///	gmp -&gt; glibc
        ///	glibc
        ///	glibc -&gt; basesystem
        ///	glibc -&gt; bash
        ///	glibc -&gt; libselinux
        ///	glibc -&gt; tzdata
        ///	basesystem
        ///	basesystem -&gt; filesystem
        ///	basesystem -&gt; setup
        ///	bash
        ///	bash -&gt; filesystem
        ///	bash -&gt; glibc
        ///	bash -&gt; ncurses
        ///	libselinux
        ///	libselinux -&gt; glibc
        ///	libselinux -&gt; pcre2
        ///	libselinux -&gt; libsepol
        ///	libselinux -&gt; python3
        ///	tzdata
        ///	pcre2
        ///	pcre2 -&gt; glibc
        ///	libsepol
        ///	libsepol -&gt; bash
        ///	libsepol -&gt; glibc
        ///	python3
        ///	python3 -&gt; bash
        ///	python3 -&gt; chkconfig [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string input_nginx {
            get {
                return ResourceManager.GetString("input_nginx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 digraph MyPicture {
        ///	graph [rankdir=LR]
        ///	mpfr
        ///	mpfr -&gt; glibc
        ///	mpfr -&gt; gmp
        ///	glibc
        ///	glibc -&gt; basesystem
        ///	glibc -&gt; bash
        ///	glibc -&gt; libselinux
        ///	glibc -&gt; tzdata
        ///	gmp
        ///	gmp -&gt; glibc
        ///	basesystem
        ///	basesystem -&gt; filesystem
        ///	basesystem -&gt; setup
        ///	bash
        ///	bash -&gt; filesystem
        ///	bash -&gt; glibc
        ///	bash -&gt; ncurses
        ///	libselinux
        ///	libselinux -&gt; glibc
        ///	libselinux -&gt; pcre2
        ///	libselinux -&gt; libsepol
        ///	libselinux -&gt; python3
        ///	tzdata
        ///	pcre2
        ///	pcre2 -&gt; glibc
        ///	libsepol
        ///	libsepol -&gt; bash
        ///	libsepol -&gt; glibc
        ///	python3
        ///	p [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string input_redis {
            get {
                return ResourceManager.GetString("input_redis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 a -&gt; b
        ///b -&gt; c
        ///c -&gt; a
        ///a -&gt; d
        ///d -&gt; c 的本地化字符串。
        /// </summary>
        internal static string input_test {
            get {
                return ResourceManager.GetString("input_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 perl-PathTools -&gt; glibc
        ///perl-Socket -&gt; glibc
        ///perl-Scalar-List-Utils -&gt; glibc
        ///perl-Unicode-Normalize -&gt; glibc
        ///perl-threads -&gt; glibc
        ///perl-threads-shared -&gt; glibc
        ///perl-Encode -&gt; glibc
        ///perl-MIME-Base64 -&gt; glibc
        ///perl-Storable -&gt; glibc
        ///groff -&gt; gcc
        ///groff -&gt; glibc
        ///sed -&gt; glibc
        ///texinfo -&gt; glibc
        ///libtirpc -&gt; glibc
        ///gawk -&gt; filesystem
        ///gawk -&gt; glibc
        ///libunistring -&gt; glibc
        ///json-c -&gt; glibc
        ///libedit -&gt; glibc
        /// 的本地化字符串。
        /// </summary>
        internal static string leap_mysql {
            get {
                return ResourceManager.GetString("leap_mysql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sed -&gt; glibc
        ///texinfo -&gt; glibc
        ///libtirpc -&gt; glibc
        ///gawk -&gt; filesystem
        ///gawk -&gt; glibc
        ///libunistring -&gt; glibc
        ///json-c -&gt; glibc
        ///libXau -&gt; glibc
        ///libxcb -&gt; glibc
        ///libX11 -&gt; glibc
        ///jbigkit -&gt; glibc
        ///libwebp -&gt; glibc
        ///libtiff -&gt; gcc
        ///libtiff -&gt; glibc
        ///libjpeg-turbo -&gt; glibc
        ///libpng -&gt; glibc
        ///freetype -&gt; bash
        ///freetype -&gt; glibc
        ///freetype -&gt; bzip2
        ///freetype -&gt; zlib
        ///fontconfig -&gt; bash
        ///fontconfig -&gt; glibc
        ///fontconfig -&gt; coreutils
        ///fontconfig -&gt; grep
        ///fontconfig -&gt; expat
        ///fontconfig -&gt; util-linux
        ///libXpm -&gt; glibc
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string leap_nginx {
            get {
                return ResourceManager.GetString("leap_nginx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 libtirpc -&gt; glibc
        ///gawk -&gt; filesystem
        ///gawk -&gt; glibc
        ///sed -&gt; glibc
        ///texinfo -&gt; glibc
        ///libutempter -&gt; glibc
        ///libunistring -&gt; glibc
        ///json-c -&gt; glibc
        ///redis -&gt; glibc
        ///redis -&gt; systemd
        /// 的本地化字符串。
        /// </summary>
        internal static string leap_redis {
            get {
                return ResourceManager.GetString("leap_redis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 perl -&gt; perl-Carp
        ///perl -&gt; perl-Exporter
        ///perl -&gt; perl-PathTools
        ///perl -&gt; perl-Socket
        ///perl -&gt; perl-File-Path
        ///perl -&gt; perl-Scalar-List-Utils
        ///perl -&gt; perl-Text-Tabs+Wrap
        ///perl -&gt; perl-Unicode-Normalize
        ///perl -&gt; perl-constant
        ///perl -&gt; perl-parent
        ///perl -&gt; perl-threads
        ///perl -&gt; perl-threads-shared
        ///perl -&gt; perl-Encode
        ///glibc -&gt; bash
        ///glibc -&gt; libselinux
        ///glibc -&gt; tzdata
        ///gcc -&gt; bash
        ///gcc -&gt; texinfo
        ///python3 -&gt; python-setuptools
        ///python3 -&gt; libtirpc
        ///python-pip -&gt; python-setuptools
        ///libnsl2 -&gt; libtirpc
        ///readl [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string reverse_mysql {
            get {
                return ResourceManager.GetString("reverse_mysql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ca-certificates -&gt; sed
        ///coreutils -&gt; acl
        ///coreutils -&gt; attr
        ///coreutils -&gt; libcap
        ///coreutils -&gt; openssl
        ///coreutils -&gt; gmp
        ///coreutils -&gt; libselinux
        ///coreutils -&gt; ncurses
        ///coreutils -&gt; bash
        ///coreutils -&gt; texinfo
        ///grep -&gt; texinfo
        ///glibc -&gt; bash
        ///glibc -&gt; libselinux
        ///glibc -&gt; tzdata
        ///filesystem -&gt; bash
        ///python3 -&gt; libtirpc
        ///libnsl2 -&gt; libtirpc
        ///readline -&gt; texinfo
        ///krb5 -&gt; gawk
        ///krb5 -&gt; sed
        ///pam -&gt; libtirpc
        ///systemd -&gt; bash
        ///systemd -&gt; shadow-utils
        ///systemd -&gt; acl
        ///systemd -&gt; dbus
        ///systemd -&gt; grep
        ///systemd -&gt; au [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string reverse_nginx {
            get {
                return ResourceManager.GetString("reverse_nginx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 glibc -&gt; bash
        ///glibc -&gt; libselinux
        ///glibc -&gt; tzdata
        ///python3 -&gt; libtirpc
        ///libnsl2 -&gt; libtirpc
        ///readline -&gt; texinfo
        ///krb5 -&gt; gawk
        ///krb5 -&gt; sed
        ///coreutils -&gt; acl
        ///coreutils -&gt; attr
        ///coreutils -&gt; libcap
        ///coreutils -&gt; openssl
        ///coreutils -&gt; gmp
        ///coreutils -&gt; libselinux
        ///coreutils -&gt; ncurses
        ///coreutils -&gt; bash
        ///coreutils -&gt; texinfo
        ///grep -&gt; texinfo
        ///filesystem -&gt; bash
        ///gcc -&gt; bash
        ///gcc -&gt; texinfo
        ///util-linux -&gt; libutempter
        ///pam -&gt; libtirpc
        ///systemd -&gt; bash
        ///systemd -&gt; shadow-utils
        ///systemd -&gt; acl
        ///systemd -&gt; dbus [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string reverse_redis {
            get {
                return ResourceManager.GetString("reverse_redis", resourceCulture);
            }
        }
    }
}
